@extends('layouts.client-area')

@section('title', __('ui.module_inventory').' | '.__('inventory_web.new_movement'))
@section('client-page-title', __('inventory_web.new_movement'))

@section('client-content')
<div class="w-full p-5 md:p-8"><x-ui.page-heading :title="__('inventory_web.new_movement')"><x-slot:actions><x-ui.button :href="route('inventory.movements.index')" variant="secondary" class="rounded-full">{{ __('inventory_web.back') }}</x-ui.button></x-slot:actions></x-ui.page-heading><x-ui.panel class="mt-6 max-w-4xl border-[var(--ui-border)] shadow-none" padding="p-5 md:p-6"><form method="POST" action="{{ route('inventory.movements.store') }}" class="grid gap-5 md:grid-cols-2">@csrf
    <x-ui.field :label="__('inventory_web.warehouse')" for="warehouse_id" :required="true" :error="$errors->first('warehouse_id')"><x-ui.select id="warehouse_id" name="warehouse_id" required :aria-describedby="$errors->has('warehouse_id') ? 'warehouse_id-error' : null"><option value="">{{ __('inventory_web.select') }}</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(old('warehouse_id') == $warehouse->id)>{{ $warehouse->code }} — {{ $warehouse->name }}</option>@endforeach</x-ui.select></x-ui.field>
    <x-ui.field :label="__('inventory_web.product')" for="product_id" :required="true" :error="$errors->first('product_id')"><x-ui.select id="product_id" name="product_id" required :aria-describedby="$errors->has('product_id') ? 'product_id-error' : null"><option value="">{{ __('inventory_web.select') }}</option>@foreach ($products as $product)<option value="{{ $product->id }}" @selected(old('product_id') == $product->id)>{{ $product->sku }} — {{ $product->description }}</option>@endforeach</x-ui.select></x-ui.field>
    <x-ui.field :label="__('inventory_web.type')" for="movement_type" :required="true" :error="$errors->first('movement_type')"><x-ui.select id="movement_type" name="movement_type" required select2="false" :aria-describedby="$errors->has('movement_type') ? 'movement_type-error' : null">@foreach ($movementTypes as $type => $label)<option value="{{ $type }}" @selected(old('movement_type', 'RECEIPT') === $type)>{{ $label }}</option>@endforeach</x-ui.select></x-ui.field>
    <x-ui.field :label="__('inventory_web.quantity')" for="quantity" :required="true" :error="$errors->first('quantity')"><x-ui.input id="quantity" name="quantity" type="number" min="0.001" step="0.001" :value="old('quantity')" required :aria-describedby="$errors->has('quantity') ? 'quantity-error' : null" /></x-ui.field>
    <x-ui.field :label="__('inventory_web.date')" for="movement_at" :required="true" :error="$errors->first('movement_at')"><x-ui.input id="movement_at" name="movement_at" type="datetime-local" :value="old('movement_at', now()->format('Y-m-d\\TH:i'))" required :aria-describedby="$errors->has('movement_at') ? 'movement_at-error' : null" /></x-ui.field>
    <x-ui.field :label="__('inventory_web.lot')" for="lot_number" :error="$errors->first('lot_number')"><x-ui.input id="lot_number" name="lot_number" :value="old('lot_number')" :aria-describedby="$errors->has('lot_number') ? 'lot_number-error' : null" /></x-ui.field>
    <x-ui.field :label="__('inventory_web.reference_type')" for="reference_type" :error="$errors->first('reference_type')"><x-ui.input id="reference_type" name="reference_type" :value="old('reference_type')" :aria-describedby="$errors->has('reference_type') ? 'reference_type-error' : null" /></x-ui.field>
    <x-ui.field :label="__('inventory_web.reference_id')" for="reference_id" :error="$errors->first('reference_id')"><x-ui.input id="reference_id" name="reference_id" type="number" min="1" :value="old('reference_id')" :aria-describedby="$errors->has('reference_id') ? 'reference_id-error' : null" /></x-ui.field>
    <x-ui.field class="md:col-span-2" :label="__('inventory_web.notes')" for="notes" :error="$errors->first('notes')"><x-ui.textarea id="notes" name="notes" rows="3" :aria-describedby="$errors->has('notes') ? 'notes-error' : null">{{ old('notes') }}</x-ui.textarea></x-ui.field>
    <div class="md:col-span-2 flex justify-end gap-3"><x-ui.button :href="route('inventory.movements.index')" variant="secondary">{{ __('inventory_web.cancel') }}</x-ui.button><x-ui.button type="submit" variant="primary">{{ __('inventory_web.save') }}</x-ui.button></div>
</form></x-ui.panel></div>
@endsection
