@extends('layouts.client-area')

@section('title', __('ui.module_inventory').' | '.__('inventory_web.movements'))
@section('client-page-title', __('inventory_web.movements'))

@section('client-content')
<div class="w-full p-5 md:p-8">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="font-display text-3xl font-bold">{{ __('inventory_web.movements') }}</h1><p class="mt-1 text-sm text-[#5f6368]">{{ __('inventory_web.movements_description') }}</p></div><x-ui.button :href="route('inventory.movements.create')" variant="brand-primary" class="rounded-full">{{ __('inventory_web.new_movement') }}</x-ui.button></div>
    @if (session('status'))<x-ui.alert class="mt-5" variant="success">{{ session('status') }}</x-ui.alert>@endif
    <x-ui.panel class="mt-6 border-[#dadce0] shadow-none" padding="p-5 md:p-6">
        <form method="GET" class="grid gap-3 md:grid-cols-4"><x-ui.select name="warehouse_id" select2="false"><option value="">{{ __('inventory_web.all_warehouses') }}</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected($warehouseId === $warehouse->id)>{{ $warehouse->code }} — {{ $warehouse->name }}</option>@endforeach</x-ui.select><x-ui.select name="product_id" select2="false"><option value="">{{ __('inventory_web.all_products') }}</option>@foreach ($products as $product)<option value="{{ $product->id }}" @selected($productId === $product->id)>{{ $product->sku }} — {{ $product->description }}</option>@endforeach</x-ui.select><x-ui.select name="movement_type" select2="false"><option value="">{{ __('inventory_web.all_types') }}</option>@foreach ($movementTypes as $type => $label)<option value="{{ $type }}" @selected($movementType === $type)>{{ $label }}</option>@endforeach</x-ui.select><x-ui.button type="submit" variant="surface-muted" class="rounded-xl">{{ __('inventory_web.filter') }}</x-ui.button></form>
        <div class="mt-6 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b border-[#dadce0] text-left text-[#5f6368]"><th class="px-3 py-3">{{ __('inventory_web.date') }}</th><th class="px-3 py-3">{{ __('inventory_web.type') }}</th><th class="px-3 py-3">{{ __('inventory_web.warehouse') }}</th><th class="px-3 py-3">{{ __('inventory_web.product') }}</th><th class="px-3 py-3 text-right">{{ __('inventory_web.quantity') }}</th><th class="px-3 py-3">{{ __('inventory_web.reference') }}</th><th class="px-3 py-3">{{ __('inventory_web.notes') }}</th></tr></thead><tbody>@forelse ($movements as $movement)<tr class="border-b border-[#f1f3f4]"><td class="px-3 py-4">{{ $movement->movement_at?->format('d/m/Y H:i') }}</td><td class="px-3 py-4">{{ $movementTypes[$movement->movement_type] ?? $movement->movement_type }}</td><td class="px-3 py-4">{{ $movement->warehouse?->code }}</td><td class="px-3 py-4">{{ $movement->product?->sku }} — {{ $movement->product?->description }}</td><td class="px-3 py-4 text-right">{{ number_format($movement->quantity, 3, ',', '.') }} {{ $movement->product?->unit?->code }}</td><td class="px-3 py-4 text-[#5f6368]">{{ $movement->reference_type ? $movement->reference_type.' #'.$movement->reference_id : '—' }}</td><td class="px-3 py-4 text-[#5f6368]">{{ $movement->notes ?: '—' }}</td></tr>@empty<tr><td colspan="7" class="px-3 py-10 text-center text-[#5f6368]">{{ __('inventory_web.empty_movements') }}</td></tr>@endforelse</tbody></table></div>
        <div class="mt-6">{{ $movements->links() }}</div>
    </x-ui.panel>
</div>
@endsection
