<?php

return [
    'pending' => 'Pendientes', 'in_progress' => 'En curso', 'no_pending' => 'No hay pendientes asignados a este dominio.', 'no_in_progress' => 'No hay elementos en curso para este dominio.', 'shortcuts' => 'Accesos de gestión', 'shortcuts_hint' => 'Acceda rápidamente a las pantallas operativas de este dominio.',
    'severity' => ['critical' => 'Crítico', 'attention' => 'Atención', 'normal' => 'Normal'],
    'descriptions' => ['engineering' => 'Vista de las estructuras de producto y proceso enfocada en pendientes técnicos y liberaciones.', 'planning' => 'Acompañe la planificación MRP y la programación de producción con foco en colas y publicación de planes.', 'shop_floor' => 'Supervise la ejecución en planta, los cuellos de botella de inicio y los asuntos de calidad abiertos.', 'analysis' => 'Acompañe indicadores operativos, recomendaciones y puntos que requieren acción inmediata.', 'inventory' => 'Control rápido de reservas, riesgos de saldo y movimientos recientes.', 'purchasing' => 'Consolide pendientes de suministros y acompañe el flujo de compras en ejecución.', 'sales' => 'Visualice rápidamente el embudo operativo de ventas y acceda a los registros principales.', 'administration' => 'Gestione accesos y gobernanza con foco en invitaciones, perfiles y pendientes administrativos.'],
    'shortcuts_labels' => ['new_schedule' => 'Nueva programación', 'generate_calendar' => 'Generar calendario', 'new_order' => 'Nueva orden de producción', 'new_movement' => 'Nuevo movimiento', 'new_sale' => 'Nuevo pedido de venta', 'new_customer' => 'Nuevo cliente'],
    'metrics' => [
        'draft_product_versions' => 'Versiones de producto en borrador con aging > :days d', 'draft_boms' => 'BOM en borrador con aging > :days d', 'draft_routings' => 'Enrutamientos en borrador con aging > :days d', 'ecos_in_progress' => 'ECO en curso', 'versions_awaiting_approval' => 'Versiones pendientes de aprobación', 'overdue_mrp_suggestions' => 'Sugerencias MRP atrasadas', 'high_priority_mrp' => 'Sugerencias MRP de alta prioridad (≤ :priority)', 'draft_schedules' => 'Programas en borrador con aging > 2 d', 'mrp_runs' => 'Ejecuciones MRP en curso', 'draft_orders_priority' => 'Órdenes en borrador pendientes de liberación prioritaria (aging > 1 d)', 'released_orders_sla' => 'Órdenes liberadas fuera del SLA (> :days d)', 'late_orders' => 'Órdenes en curso atrasadas respecto al fin planificado', 'open_reworks' => 'Retrabajos abiertos con aging > :days d', 'orders_in_progress' => 'Órdenes en curso', 'pending_quality' => 'Registros de calidad pendientes', 'pending_recommendations' => 'Recomendaciones pendientes con aging > :days d', 'quality_closing' => 'Calidad pendiente de cierre', 'partial_postings' => 'Órdenes con partes parciales', 'today_postings' => 'Partes de hoy', 'high_priority_reservations' => 'Reservas de alta prioridad (≤ 20)', 'expired_reservations' => 'Reservas vencidas aún activas', 'low_stock' => 'Artículos por debajo del stock de seguridad', 'today_movements' => 'Movimientos de hoy', 'today_transfers' => 'Transferencias de hoy', 'inspection_items' => 'Artículos en inspección', 'overdue_requisition_lines' => 'Líneas de solicitud vencidas (necesidad < hoy)', 'late_purchase_orders' => 'Pedidos de compra con entrega atrasada', 'draft_receipts' => 'Recepciones en borrador con aging > 2 d', 'open_purchase_orders' => 'Pedidos de compra abiertos', 'urgent_requisition_lines' => 'Líneas de solicitud urgentes (necesidad ≤ D+3)', 'draft_sales' => 'Pedidos en borrador', 'pending_sales_sla' => 'Pedidos confirmados pendientes fuera del SLA (> :days d)', 'pending_sales_total' => 'Pedidos confirmados pendientes (total)', 'sales_in_fulfillment' => 'Pedidos en separación/facturación/expedición', 'shipped_sales_aging' => 'Pedidos expedidos con aging > 2 d', 'pending_invitations_sla' => 'Invitaciones pendientes fuera del SLA (> :days d)', 'pending_access_approvals' => 'Aprobaciones de acceso pendientes con aging > 2 d', 'active_company_users' => 'Usuarios activos con acceso a la empresa', 'today_invitations' => 'Invitaciones enviadas hoy',
    ],
];
