<?php

return [
    'select' => 'Seleccione', 'filter' => 'Filtrar', 'all' => 'Todos', 'all_statuses' => 'Todos los estados', 'active' => 'Activo', 'inactive' => 'Inactivo', 'edit' => 'Editar', 'status' => 'Estado', 'product' => 'Producto', 'warehouse' => 'Almacén', 'plant' => 'Planta', 'type' => 'Tipo', 'code' => 'Código', 'name' => 'Nombre', 'date' => 'Fecha', 'notes' => 'Observaciones', 'sequence' => 'Sec.', 'operation' => 'Operación', 'work_center' => 'Centro de trabajo', 'capacity' => 'Capacidad', 'capacity_per_day' => 'Capacidad/día', 'efficiency' => 'Eficiencia', 'description' => 'Descripción', 'version' => 'Versión', 'effective_from' => 'Vigencia inicial', 'effective_to' => 'Vigencia final', 'save' => 'Guardar', 'yes' => 'Sí', 'no' => 'No', 'select_product' => 'Seleccione un producto', 'select_warehouse' => 'Seleccione un almacén', 'select_work_center' => 'Seleccione un centro de trabajo',
    'orders' => [
        'sale_context' => 'Esta OP se vinculará a la venta #:sale y aparecerá en el seguimiento del pedido.',
        'invalid_sale_context' => 'El contexto de la venta no es válido para esta orden de producción.',
        'new' => 'Nueva orden de producción', 'new_short' => 'Nueva orden', 'create' => 'Crear orden', 'search' => 'Buscar por orden, venta, SKU o producto', 'number' => 'Orden', 'sale_number' => 'N.º de venta', 'input_warehouse' => 'Almacén de entrada (producto terminado)', 'planned_quantity' => 'Cantidad planificada', 'planned' => 'Planificado', 'produced' => 'Producido', 'scrap' => 'Desecho', 'scheduled_start' => 'Inicio previsto', 'scheduled_end' => 'Fin previsto', 'empty' => 'No se encontraron órdenes.', 'release' => 'Liberar orden', 'complete' => 'Completar orden', 'posting_title' => 'Registrar parte de producción', 'posting_hint' => 'Use este formulario para registrar producción parcial y desecho por operación.', 'good_quantity' => 'Cant. producida', 'scrap_quantity' => 'Cant. desechada', 'finished_lot' => 'Lote de producto terminado', 'setup_time' => 'Preparación (HH:MM)', 'process_time' => 'Proceso (HH:MM)', 'inspection_status' => 'Estado de inspección', 'inspection_notes' => 'Notas de inspección', 'consumption_title' => 'Registrar consumo', 'consumption_hint' => 'Ajuste la cantidad planificada o registre explícitamente un consumo adicional.', 'planned_products' => 'Productos previstos en la BOM', 'planned_consumed_balance' => 'Previsto: :planned · Consumido: :consumed · Saldo: :balance', 'confirm_quantity' => 'Confirmar cantidad', 'confirm' => 'Confirmar', 'no_planned_components' => 'No se encontraron componentes previstos en la BOM congelada.', 'additional_consumption' => 'Agregar consumo adicional', 'unplanned_product' => 'Producto no previsto', 'quantity' => 'Cantidad', 'lot' => 'Lote', 'record_additional' => 'Registrar adicional', 'inspection_checkpoints' => 'Puntos de inspección', 'posting_reference' => 'Parte #:id · Operación :operation', 'good_and_scrap' => 'Buena: :good · Desecho: :scrap', 'update_checkpoint' => 'Actualizar punto de control', 'no_postings' => 'Aún no hay partes registrados.', 'latest_consumptions' => 'Últimos consumos', 'additional_consumptions' => 'Consumos adicionales de esta OP', 'consumption_summary' => 'Almacén: :warehouse · Consumo: :consumption · Desecho: :scrap', 'additional' => 'Adicional', 'no_consumptions' => 'No hay consumos registrados.', 'analytics' => 'Indicadores', 'created' => 'Orden de producción creada correctamente.', 'released' => 'Orden liberada para ejecución.', 'completed' => 'Orden completada correctamente.', 'posting_required' => 'Informe una cantidad producida o desechada.', 'posting_created' => 'Parte de producción registrado correctamente.', 'consumption_created' => 'Consumo registrado correctamente.', 'inspection_updated' => 'Punto de inspección actualizado.',
    ],
    'routing' => [
        'new' => 'Nuevo enrutamiento', 'edit' => 'Editar enrutamiento', 'new_version' => 'Nueva versión', 'search' => 'Buscar por versión, SKU, producto o descripción', 'operations' => 'Operaciones', 'empty_versions' => 'No se encontraron versiones.', 'title' => 'Enrutamiento #:id', 'approve' => 'Aprobar enrutamiento', 'add_operation' => 'Agregar operación', 'operation_number' => 'Número de operación', 'operation_code' => 'Código de operación', 'operation_name' => 'Nombre de operación', 'runtime' => 'Ejecución (HH:MM)', 'queue' => 'Cola (HH:MM)', 'move' => 'Movimiento (HH:MM)', 'outsourced' => 'Tercerizada', 'total_time' => 'Tiempo total (HH:MM)', 'empty_operations' => 'No hay operaciones registradas.', 'create' => 'Crear enrutamiento', 'created' => 'Versión de enrutamiento creada.', 'draft_only' => 'Solo se pueden editar versiones DRAFT.', 'updated' => 'Versión de enrutamiento actualizada.', 'operation_added' => 'Operación agregada al enrutamiento.', 'approved' => 'Enrutamiento aprobado correctamente.',
    ],
    'work_centers' => [
        'new' => 'Nuevo centro de trabajo', 'new_short' => 'Nuevo centro', 'edit' => 'Editar centro de trabajo', 'create' => 'Crear centro', 'search' => 'Buscar por código, nombre o tipo', 'machine' => 'Máquina', 'line' => 'Línea', 'empty' => 'No se encontraron centros.', 'add_shift' => 'Agregar turno', 'shift_name' => 'Nombre del turno', 'shift_start' => 'Inicio', 'shift_end' => 'Fin', 'shift_capacity' => 'Capacidad (horas)', 'save_shift' => 'Guardar turno', 'registered_shifts' => 'Turnos registrados', 'shift_summary' => 'Capacidad: :capacity h | :status', 'no_shifts' => 'No hay turnos registrados.', 'latest_calendar_days' => 'Últimos días del calendario', 'working_day' => 'Día laborable', 'no_days' => 'No hay días registrados.', 'created' => 'Centro de trabajo creado.', 'updated' => 'Centro de trabajo actualizado.', 'shift_added' => 'Turno agregado correctamente.',
    ],
    'calendar' => [
        'new' => 'Nuevo día de calendario', 'new_short' => 'Nuevo día', 'edit' => 'Editar día de calendario', 'create' => 'Crear día', 'available_capacity' => 'Capacidad disponible', 'from' => 'Desde', 'until' => 'Hasta', 'generate' => 'Generar calendario para el período', 'empty' => 'No hay datos para el filtro informado.', 'day_title' => 'Día :date', 'created' => 'Día de calendario creado.', 'updated' => 'Día de calendario actualizado.', 'generated' => 'Calendario generado correctamente.',
    ],
    'scheduling' => [
        'new' => 'Nueva programación', 'edit' => 'Editar parámetros de programación', 'description' => 'Este módulo ejecuta programación finita/infinita según las órdenes liberadas y las instantáneas de enrutamiento.', 'sale' => 'Venta: :reference', 'result' => 'Resultado de la programación', 'edit_parameters' => 'Editar parámetros', 'reference_date' => 'Fecha de referencia', 'mode' => 'Modo', 'direction' => 'Dirección', 'rule' => 'Regla', 'selected_orders' => 'Órdenes seleccionadas', 'calculated_sequence' => 'Secuenciación calculada', 'center' => 'Centro', 'start' => 'Inicio', 'end' => 'Fin', 'duration' => 'Duración (HH:MM)', 'completed' => 'Programación ejecutada correctamente.',
    ],
    'analytics' => [
        'title' => 'Indicadores de producción', 'orders' => 'Órdenes de producción', 'period' => 'Período', 'days' => ':count días', 'update' => 'Actualizar', 'plan_adherence' => 'Adherencia al plan', 'quality_rate' => 'Tasa de calidad', 'setup_time' => 'Tiempo de preparación', 'process_time' => 'Tiempo de proceso', 'orders_by_status' => 'Órdenes por estado', 'scrap_by_day' => 'Desecho por día', 'total_scrap' => 'Desecho total', 'no_period_records' => 'No hay registros en el período.', 'efficiency_by_operation' => 'Eficiencia por operación', 'good_quantity' => 'Cant. buena', 'process_time_hhmm' => 'Tiempo de proceso (HH:MM)', 'productivity' => 'Productividad (cant./min)', 'no_operation_data' => 'No hay datos de operación en el período.',
    ],
    'status_labels' => ['DRAFT' => 'Borrador', 'RELEASED' => 'Liberada', 'IN_PROGRESS' => 'En curso', 'PARTIALLY_COMPLETED' => 'Parcialmente completada', 'COMPLETED' => 'Completada', 'CANCELLED' => 'Cancelada', 'APPROVED' => 'Aprobado', 'PENDING' => 'Pendiente', 'REJECTED' => 'Rechazado', 'OBSOLETE' => 'Obsoleta'],
];
