<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Identity\Infrastructure\Persistence\Models\Permission;
use App\Modules\Identity\Infrastructure\Persistence\Models\Role;
use App\Modules\Tenant\Infrastructure\Persistence\Models\Company;
use Illuminate\Database\Seeder;

final class TenantRolesSeeder extends Seeder
{
    public function run(): void
    {
        $roleMatrix = [
            'planner' => [
                'name' => 'Planner',
                'permissions' => [
                    'work-centers.read',
                    'production-calendar.read',
                    'production-calendar.generate',
                    'production-scheduling.run',
                    'bom.explode',
                    'mrp.plan',
                    'routing-versions.read',
                    'routing-operations.read',
                    'inventory.read',
                    'inventory.plants.read',
                    'inventory.warehouses.read',
                    'admin-data.branches.read',
                    'admin-data.warehouse-locations.read',
                    'admin-data.departments.read',
                    'admin-data.cost-centers.read',
                    'admin-data.units.read',
                    'admin-data.categories.read',
                    'admin-data.brands.read',
                    'admin-data.ncms.read',
                    'admin-data.cfops.read',
                    'admin-data.taxes.read',
                    'inventory.lots.read',
                    'inventory.lots.trace',
                    'inventory.serials.read',
                    'inventory.serials.trace',
                    'production-orders.read',
                    'production-orders.consumption.read',
                    'genealogy.trace',
                    'eco.read',
                    'eco.create',
                    'eco.update',
                    'eco.submit',
                    'eco.impact.read',
                    'purchasing.suppliers.read',
                    'purchasing.requisitions.read',
                    'purchasing.requisitions.create',
                    'purchasing.quotations.read',
                    'purchasing.receipts.read',
                    'purchasing.fiscal-entries.read',
                    'purchasing.requisitions.from-mrp',
                    'purchasing.orders.read',
                    'sales.customers.read',
                    'sales.read',
                    'company-access.dashboard.read',
                    'company-access.billing.read',
                    'company-access.billing.update',
                ],
            ],
            'supervisor' => [
                'name' => 'Supervisor',
                'permissions' => [
                    'work-centers.read',
                    'work-centers.create',
                    'work-centers.update',
                    'work-centers.shifts.create',
                    'production-calendar.read',
                    'production-calendar.update',
                    'production-calendar.generate',
                    'production-scheduling.run',
                    'bom.explode',
                    'mrp.plan',
                    'routing-versions.read',
                    'routing-versions.create',
                    'routing-versions.approve',
                    'routing-operations.read',
                    'routing-operations.create',
                    'routing-operations.update',
                    'inventory.read',
                    'inventory.update',
                    'inventory.plants.read',
                    'inventory.plants.create',
                    'inventory.plants.update',
                    'inventory.warehouses.read',
                    'inventory.warehouses.create',
                    'inventory.warehouses.update',
                    'admin-data.branches.read',
                    'admin-data.branches.create',
                    'admin-data.branches.update',
                    'admin-data.warehouse-locations.read',
                    'admin-data.warehouse-locations.create',
                    'admin-data.warehouse-locations.update',
                    'admin-data.departments.read',
                    'admin-data.departments.create',
                    'admin-data.departments.update',
                    'admin-data.cost-centers.read',
                    'admin-data.cost-centers.create',
                    'admin-data.cost-centers.update',
                    'admin-data.units.read',
                    'admin-data.units.create',
                    'admin-data.units.update',
                    'admin-data.categories.read',
                    'admin-data.categories.create',
                    'admin-data.categories.update',
                    'admin-data.brands.read',
                    'admin-data.brands.create',
                    'admin-data.brands.update',
                    'admin-data.ncms.read',
                    'admin-data.ncms.create',
                    'admin-data.ncms.update',
                    'admin-data.cfops.read',
                    'admin-data.cfops.create',
                    'admin-data.cfops.update',
                    'admin-data.taxes.read',
                    'admin-data.taxes.create',
                    'admin-data.taxes.update',
                    'inventory.lots.read',
                    'inventory.lots.create',
                    'inventory.lots.trace',
                    'inventory.serials.read',
                    'inventory.serials.create',
                    'inventory.serials.trace',
                    'production-orders.read',
                    'production-orders.create',
                    'production-orders.release',
                    'production-orders.partial',
                    'production-orders.complete',
                    'production-orders.consumption.create',
                    'production-orders.consumption.read',
                    'genealogy.trace',
                    'genealogy.relations.create',
                    'eco.read',
                    'eco.create',
                    'eco.update',
                    'eco.submit',
                    'eco.impact.read',
                    'purchasing.suppliers.read',
                    'purchasing.suppliers.create',
                    'purchasing.suppliers.update',
                    'purchasing.supplier-rules.manage',
                    'purchasing.requisitions.read',
                    'purchasing.requisitions.create',
                    'purchasing.requisitions.update',
                    'purchasing.requisitions.from-mrp',
                    'purchasing.requisitions.convert',
                    'purchasing.orders.read',
                    'purchasing.orders.create',
                    'purchasing.orders.update',
                    'purchasing.quotations.read',
                    'purchasing.quotations.create',
                    'purchasing.quotations.update',
                    'purchasing.receipts.read',
                    'purchasing.receipts.create',
                    'purchasing.receipts.update',
                    'purchasing.fiscal-entries.read',
                    'purchasing.fiscal-entries.create',
                    'purchasing.fiscal-entries.update',
                    'sales.customers.read',
                    'sales.customers.create',
                    'sales.customers.update',
                    'sales.read',
                    'sales.create',
                    'sales.update',
                    'company-access.dashboard.read',
                    'company-access.billing.read',
                    'company-access.billing.update',
                ],
            ],
            'master' => [
                'name' => 'Master',
                'permissions' => [
                    'work-centers.read',
                    'work-centers.create',
                    'work-centers.update',
                    'work-centers.delete',
                    'work-centers.shifts.create',
                    'production-calendar.read',
                    'production-calendar.update',
                    'production-calendar.generate',
                    'production-scheduling.run',
                    'bom.explode',
                    'mrp.plan',
                    'routing-versions.read',
                    'routing-versions.create',
                    'routing-versions.approve',
                    'routing-versions.obsolete',
                    'routing-operations.read',
                    'routing-operations.create',
                    'routing-operations.update',
                    'routing-operations.delete',
                    'inventory.read',
                    'inventory.update',
                    'inventory.plants.read',
                    'inventory.plants.create',
                    'inventory.plants.update',
                    'inventory.warehouses.read',
                    'inventory.warehouses.create',
                    'inventory.warehouses.update',
                    'admin-data.branches.read',
                    'admin-data.branches.create',
                    'admin-data.branches.update',
                    'admin-data.warehouse-locations.read',
                    'admin-data.warehouse-locations.create',
                    'admin-data.warehouse-locations.update',
                    'admin-data.departments.read',
                    'admin-data.departments.create',
                    'admin-data.departments.update',
                    'admin-data.cost-centers.read',
                    'admin-data.cost-centers.create',
                    'admin-data.cost-centers.update',
                    'admin-data.units.read',
                    'admin-data.units.create',
                    'admin-data.units.update',
                    'admin-data.categories.read',
                    'admin-data.categories.create',
                    'admin-data.categories.update',
                    'admin-data.brands.read',
                    'admin-data.brands.create',
                    'admin-data.brands.update',
                    'admin-data.ncms.read',
                    'admin-data.ncms.create',
                    'admin-data.ncms.update',
                    'admin-data.cfops.read',
                    'admin-data.cfops.create',
                    'admin-data.cfops.update',
                    'admin-data.taxes.read',
                    'admin-data.taxes.create',
                    'admin-data.taxes.update',
                    'inventory.lots.read',
                    'inventory.lots.create',
                    'inventory.lots.trace',
                    'inventory.serials.read',
                    'inventory.serials.create',
                    'inventory.serials.trace',
                    'production-orders.read',
                    'production-orders.create',
                    'production-orders.release',
                    'production-orders.partial',
                    'production-orders.complete',
                    'production-orders.consumption.create',
                    'production-orders.consumption.read',
                    'genealogy.trace',
                    'genealogy.relations.create',
                    'eco.read',
                    'eco.create',
                    'eco.update',
                    'eco.submit',
                    'eco.approve',
                    'eco.reject',
                    'eco.implement',
                    'eco.impact.read',
                    'purchasing.suppliers.read',
                    'purchasing.suppliers.create',
                    'purchasing.suppliers.update',
                    'purchasing.supplier-rules.manage',
                    'purchasing.requisitions.read',
                    'purchasing.requisitions.create',
                    'purchasing.requisitions.update',
                    'purchasing.requisitions.from-mrp',
                    'purchasing.requisitions.convert',
                    'purchasing.orders.read',
                    'purchasing.orders.create',
                    'purchasing.orders.update',
                    'purchasing.orders.approve',
                    'purchasing.quotations.read',
                    'purchasing.quotations.create',
                    'purchasing.quotations.update',
                    'purchasing.receipts.read',
                    'purchasing.receipts.create',
                    'purchasing.receipts.update',
                    'purchasing.fiscal-entries.read',
                    'purchasing.fiscal-entries.create',
                    'purchasing.fiscal-entries.update',
                    'sales.customers.read',
                    'sales.customers.create',
                    'sales.customers.update',
                    'sales.read',
                    'sales.create',
                    'sales.update',
                    'company-access.users.read',
                    'company-access.users.create',
                    'company-access.users.update',
                    'company-access.users.delete',
                    'company-access.rbac.read',
                    'company-access.roles.create',
                    'company-access.roles.update',
                    'company-access.roles.delete',
                    'company-access.dashboard.read',
                    'company-access.billing.read',
                    'company-access.billing.update',
                ],
            ],
        ];

        $permissionIdsBySlug = Permission::query()
            ->whereIn('slug', collect($roleMatrix)->pluck('permissions')->flatten()->unique()->values())
            ->pluck('id', 'slug');

        Company::query()->each(function (Company $company) use ($roleMatrix, $permissionIdsBySlug): void {
            foreach ($roleMatrix as $roleSlug => $definition) {
                $role = Role::query()->updateOrCreate(
                    [
                        'company_id' => $company->id,
                        'slug' => $roleSlug,
                    ],
                    [
                        'name' => $definition['name'],
                    ]
                );

                $rolePermissionIds = collect($definition['permissions'])
                    ->map(static fn (string $slug): ?int => $permissionIdsBySlug->get($slug))
                    ->filter()
                    ->values()
                    ->all();

                $role->permissions()->sync($rolePermissionIds);
            }
        });
    }
}
