<?php

return [
    'pending' => 'Pending', 'in_progress' => 'In progress', 'no_pending' => 'No pending items mapped for this domain.', 'no_in_progress' => 'No in-progress items for this domain.', 'shortcuts' => 'Management shortcuts', 'shortcuts_hint' => 'Quickly access this domain’s operational screens.',
    'severity' => ['critical' => 'Critical', 'attention' => 'Attention', 'normal' => 'Normal'],
    'descriptions' => ['engineering' => 'Product and process structure overview focused on technical pending items and releases.', 'planning' => 'Track MRP planning and production scheduling with a focus on queues and plan publishing.', 'shop_floor' => 'Monitor shop-floor execution, startup bottlenecks and open quality items.', 'analysis' => 'Track operational indicators, recommendations and points requiring immediate action.', 'inventory' => 'Quick control of reservations, balance risks and recent movements.', 'purchasing' => 'Consolidate supply pending items and track the purchasing flow in progress.', 'sales' => 'Quickly view the operational sales funnel and access key records.', 'administration' => 'Manage access and governance with a focus on invitations, roles and administrative pending items.'],
    'shortcuts_labels' => ['new_schedule' => 'New schedule', 'generate_calendar' => 'Generate calendar', 'new_order' => 'New production order', 'new_movement' => 'New movement', 'new_sale' => 'New sales order', 'new_customer' => 'New customer'],
    'metrics' => [
        'draft_product_versions' => 'Draft product versions aging > :days d', 'draft_boms' => 'Draft BOMs aging > :days d', 'draft_routings' => 'Draft routings aging > :days d', 'ecos_in_progress' => 'ECOs in progress', 'versions_awaiting_approval' => 'Versions awaiting approval', 'overdue_mrp_suggestions' => 'Overdue MRP suggestions', 'high_priority_mrp' => 'High-priority MRP suggestions (≤ :priority)', 'draft_schedules' => 'Draft schedules aging > 2 d', 'mrp_runs' => 'MRP runs in progress', 'draft_orders_priority' => 'Draft orders awaiting priority release (aging > 1 d)', 'released_orders_sla' => 'Released orders past SLA (> :days d)', 'late_orders' => 'In-progress orders late against planned end', 'open_reworks' => 'Open rework orders aging > :days d', 'orders_in_progress' => 'Orders in progress', 'pending_quality' => 'Pending quality records', 'pending_recommendations' => 'Pending recommendations aging > :days d', 'quality_closing' => 'Quality pending closure', 'partial_postings' => 'Orders with partial postings', 'today_postings' => 'Today’s postings', 'high_priority_reservations' => 'High-priority reservations (≤ 20)', 'expired_reservations' => 'Expired reservations still active', 'low_stock' => 'Items below safety stock', 'today_movements' => 'Today’s movements', 'today_transfers' => 'Today’s transfers', 'inspection_items' => 'Items under inspection', 'overdue_requisition_lines' => 'Overdue requisition lines (need date < today)', 'late_purchase_orders' => 'Purchase orders with late delivery', 'draft_receipts' => 'Draft receipts aging > 2 d', 'open_purchase_orders' => 'Open purchase orders', 'urgent_requisition_lines' => 'Urgent requisition lines (need date ≤ D+3)', 'draft_sales' => 'Draft sales orders', 'pending_sales_sla' => 'Pending confirmed sales past SLA (> :days d)', 'pending_sales_total' => 'Pending confirmed sales (total)', 'sales_in_fulfillment' => 'Orders in picking/invoicing/shipping', 'shipped_sales_aging' => 'Shipped orders aging > 2 d', 'pending_invitations_sla' => 'Pending invitations past SLA (> :days d)', 'pending_access_approvals' => 'Pending access approvals aging > 2 d', 'active_company_users' => 'Active users with company access', 'today_invitations' => 'Invitations sent today',
    ],
];
