<?php

return [
    'select' => 'Select', 'filter' => 'Filter', 'all' => 'All', 'all_statuses' => 'All statuses', 'active' => 'Active', 'inactive' => 'Inactive', 'edit' => 'Edit', 'status' => 'Status', 'product' => 'Product', 'warehouse' => 'Warehouse', 'plant' => 'Plant', 'type' => 'Type', 'code' => 'Code', 'name' => 'Name', 'date' => 'Date', 'notes' => 'Notes', 'sequence' => 'Seq.', 'operation' => 'Operation', 'work_center' => 'Work center', 'capacity' => 'Capacity', 'capacity_per_day' => 'Capacity/day', 'efficiency' => 'Efficiency', 'description' => 'Description', 'version' => 'Version', 'effective_from' => 'Effective from', 'effective_to' => 'Effective to', 'save' => 'Save', 'yes' => 'Yes', 'no' => 'No', 'select_product' => 'Select a product', 'select_warehouse' => 'Select a warehouse', 'select_work_center' => 'Select a work center',
    'orders' => [
        'sale_context' => 'This production order will be linked to sale #:sale and shown in its tracking page.',
        'invalid_sale_context' => 'The sale context is not valid for this production order.',
        'new' => 'New production order', 'new_short' => 'New order', 'create' => 'Create order', 'search' => 'Search by order, sale, SKU or product', 'number' => 'Order', 'sale_number' => 'Sale no.', 'input_warehouse' => 'Receipt warehouse (finished goods)', 'planned_quantity' => 'Planned quantity', 'planned' => 'Planned', 'produced' => 'Produced', 'scrap' => 'Scrap', 'scheduled_start' => 'Scheduled start', 'scheduled_end' => 'Scheduled end', 'empty' => 'No orders found.', 'release' => 'Release order', 'complete' => 'Complete order', 'posting_title' => 'Record production posting', 'posting_hint' => 'Use this form to record partial production and scrap by operation.', 'good_quantity' => 'Produced qty.', 'scrap_quantity' => 'Scrap qty.', 'finished_lot' => 'Finished goods lot', 'setup_time' => 'Setup (HH:MM)', 'process_time' => 'Process (HH:MM)', 'inspection_status' => 'Inspection status', 'inspection_notes' => 'Inspection notes', 'consumption_title' => 'Record consumption', 'consumption_hint' => 'Adjust the planned quantity or explicitly record additional consumption.', 'planned_products' => 'Products planned in the BOM', 'planned_consumed_balance' => 'Planned: :planned · Consumed: :consumed · Balance: :balance', 'confirm_quantity' => 'Confirm quantity', 'confirm' => 'Confirm', 'no_planned_components' => 'No planned components were found in the frozen BOM.', 'additional_consumption' => 'Add additional consumption', 'unplanned_product' => 'Unplanned product', 'quantity' => 'Quantity', 'lot' => 'Lot', 'record_additional' => 'Record additional', 'inspection_checkpoints' => 'Inspection checkpoints', 'posting_reference' => 'Posting #:id · Operation :operation', 'good_and_scrap' => 'Good: :good · Scrap: :scrap', 'update_checkpoint' => 'Update checkpoint', 'no_postings' => 'No postings recorded yet.', 'latest_consumptions' => 'Latest consumptions', 'additional_consumptions' => 'Additional consumptions for this PO', 'consumption_summary' => 'Warehouse: :warehouse · Consumption: :consumption · Scrap: :scrap', 'additional' => 'Additional', 'no_consumptions' => 'No consumption recorded.', 'analytics' => 'Analytics', 'created' => 'Production order created successfully.', 'released' => 'Order released for execution.', 'completed' => 'Order completed successfully.', 'posting_required' => 'Enter a produced or scrapped quantity.', 'posting_created' => 'Production posting recorded successfully.', 'consumption_created' => 'Consumption recorded successfully.', 'inspection_updated' => 'Inspection checkpoint updated.',
    ],
    'routing' => [
        'new' => 'New routing', 'edit' => 'Edit routing', 'new_version' => 'New version', 'search' => 'Search by version, SKU, product or description', 'operations' => 'Operations', 'empty_versions' => 'No versions found.', 'title' => 'Routing #:id', 'approve' => 'Approve routing', 'add_operation' => 'Add operation', 'operation_number' => 'Operation number', 'operation_code' => 'Operation code', 'operation_name' => 'Operation name', 'runtime' => 'Runtime (HH:MM)', 'queue' => 'Queue (HH:MM)', 'move' => 'Move (HH:MM)', 'outsourced' => 'Outsourced', 'total_time' => 'Total time (HH:MM)', 'empty_operations' => 'No operations registered.', 'create' => 'Create routing', 'created' => 'Routing version created.', 'draft_only' => 'Only DRAFT versions can be edited.', 'updated' => 'Routing version updated.', 'operation_added' => 'Operation added to the routing.', 'approved' => 'Routing approved successfully.',
    ],
    'work_centers' => [
        'new' => 'New work center', 'new_short' => 'New center', 'edit' => 'Edit work center', 'create' => 'Create center', 'search' => 'Search by code, name or type', 'machine' => 'Machine', 'line' => 'Line', 'empty' => 'No work centers found.', 'add_shift' => 'Add shift', 'shift_name' => 'Shift name', 'shift_start' => 'Start', 'shift_end' => 'End', 'shift_capacity' => 'Capacity (hours)', 'save_shift' => 'Save shift', 'registered_shifts' => 'Registered shifts', 'shift_summary' => 'Capacity: :capacity h | :status', 'no_shifts' => 'No shifts registered.', 'latest_calendar_days' => 'Latest calendar days', 'working_day' => 'Working day', 'no_days' => 'No days registered.', 'created' => 'Work center created.', 'updated' => 'Work center updated.', 'shift_added' => 'Shift added successfully.',
    ],
    'calendar' => [
        'new' => 'New calendar day', 'new_short' => 'New day', 'edit' => 'Edit calendar day', 'create' => 'Create day', 'available_capacity' => 'Available capacity', 'from' => 'From', 'until' => 'Until', 'generate' => 'Generate calendar for period', 'empty' => 'No data for the selected filter.', 'day_title' => 'Day :date', 'created' => 'Calendar day created.', 'updated' => 'Calendar day updated.', 'generated' => 'Calendar generated successfully.',
    ],
    'scheduling' => [
        'new' => 'New schedule', 'edit' => 'Edit scheduling parameters', 'description' => 'This module runs finite/infinite scheduling based on released orders and routing snapshots.', 'sale' => 'Sale: :reference', 'result' => 'Scheduling result', 'edit_parameters' => 'Edit parameters', 'reference_date' => 'Reference date', 'mode' => 'Mode', 'direction' => 'Direction', 'rule' => 'Rule', 'selected_orders' => 'Selected orders', 'calculated_sequence' => 'Calculated sequence', 'center' => 'Center', 'start' => 'Start', 'end' => 'End', 'duration' => 'Duration (HH:MM)', 'completed' => 'Scheduling completed successfully.',
    ],
    'analytics' => [
        'title' => 'Production analytics', 'orders' => 'Production orders', 'period' => 'Period', 'days' => ':count days', 'update' => 'Update', 'plan_adherence' => 'Plan adherence', 'quality_rate' => 'Quality rate', 'setup_time' => 'Setup time', 'process_time' => 'Process time', 'orders_by_status' => 'Orders by status', 'scrap_by_day' => 'Scrap by day', 'total_scrap' => 'Total scrap', 'no_period_records' => 'No records in the period.', 'efficiency_by_operation' => 'Efficiency by operation', 'good_quantity' => 'Good qty.', 'process_time_hhmm' => 'Process time (HH:MM)', 'productivity' => 'Productivity (qty./min)', 'no_operation_data' => 'No operation data in the period.',
    ],
    'status_labels' => ['DRAFT' => 'Draft', 'RELEASED' => 'Released', 'IN_PROGRESS' => 'In progress', 'PARTIALLY_COMPLETED' => 'Partially completed', 'COMPLETED' => 'Completed', 'CANCELLED' => 'Cancelled', 'APPROVED' => 'Approved', 'PENDING' => 'Pending', 'REJECTED' => 'Rejected', 'OBSOLETE' => 'Obsolete'],
];
